### PR TITLE
Process new 3DS data

### PR DESCRIPTION
**Pull request by shutterbug2000**
Process large amount of 3DS data.

### CODE REVIEW

**Comment by jonbarrow** [comment]
I know we talked about this on Discord, just commenting this here as well for transparency purposes

This looks good! The tabs got swapped with spaces though and the title IDs need to be uppercased. Besides that this is awesome!

**Comment by jonbarrow** [comment]
Needs to be rebased with the changes made in #13 as well

**Comment by shutterbug2000** [comment]
(didn't mean to close it, thanks github very cool)

**Comment by shutterbug2000** [comment]
Fixed the issues mentioned, re-opening :p

**Pull request merged**
